# -*- coding: utf-8 -*-
"""Recommendation Model.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1P0LxHK4fDzW-kYsNJG3q8XwFfiaE9kMI
"""

import pandas as pd
import numpy as np
from scipy.sparse import csr_matrix
from sklearn.neighbors import NearestNeighbors
import matplotlib.pyplot as plt
import seaborn as sns


place = pd.read_csv("places.csv")
ratings = pd.read_csv("ratings.csv")

place.head()

ratings.head()

final_dataset = ratings.pivot(index='placeId',columns='user_id',values='ratings')
final_dataset.head()

final_dataset.fillna(0,inplace=True)
final_dataset.head()

csr_data = csr_matrix(final_dataset.values)
final_dataset.reset_index(inplace=True)
final_dataset

knn = NearestNeighbors(metric='cosine', algorithm='auto', n_neighbors=5, n_jobs=-1)
knn.fit(csr_data)


import pickle
with open('trained_model.pkl', 'wb') as f:
    pickle.dump(knn, f)
with open('trained_model.pkl', 'rb') as f:
    clf_loaded = pickle.load(f)
clf_loaded


